### ISSUE TITLE
SwiftMQ AMQP 1.0 Java client swallows InterruptedException

### ISSUE THREAD

**Issue by fross** [iitsoftware/swiftmq-client#30]
It looks like SwiftMQ AMQP 1.0 Java client swallows InterruptedException and might prevent proper thread termination if the termination logic is based on the thread interrupt status.

**Environment:**
- swiftmq-client 12.0.2
- Java 8
- Windows 10
- RabbitMQ 3.8.0

**Console output (see code below):**
```
press ENTER to interrupt thread

interrupted(before connect) ? true
interrupted(after connect) ? false
interrupted(before session) ? true
interrupted(after session) ? false
interrupted(before consumer) ? true
interrupted(after consumer) ? false

```
**Code demonstrating the issue:**
```
import java.util.Scanner;
import java.util.concurrent.TimeUnit;

import com.swiftmq.amqp.AMQPContext;
import com.swiftmq.amqp.v100.client.AMQPException;
import com.swiftmq.amqp.v100.client.Connection;
import com.swiftmq.amqp.v100.client.Consumer;
import com.swiftmq.amqp.v100.client.Session;

public class Main {

	public static void main(String[] args) {
		Thread t = new MyThread();
		t.start();

		System.out.println("press ENTER to interrupt thread");
		try (Scanner scanner = new Scanner(System.in)) {
			scanner.hasNextLine();
		}

		t.interrupt();

		try {
			t.join();
		} catch (InterruptedException e) {
			Thread.currentThread().interrupt();
		}
	}

	private static class MyThread extends Thread {
		@Override
		public void run() {
			waitForInterrupt();

			Connection connection = null;
			Session session = null;
			Consumer consumer = null;

			try {
				System.out.println("interrupted(before connect) ? " + isInterrupted());
				AMQPContext ctx = new AMQPContext(AMQPContext.CLIENT);
				connection = new Connection(ctx, "localhost", 5672, false);
				connection.connect();
				System.out.println("interrupted(after connect) ? " + isInterrupted());

				interrupt();
				System.out.println("interrupted(before session) ? " + isInterrupted());
				session = connection.createSession(100, 100);
				System.out.println("interrupted(after session) ? " + isInterrupted());

				interrupt();
				System.out.println("interrupted(before consumer) ? " + isInterrupted());
				consumer = session.createConsumer("/exchange/my-exchange", 100, 0, true, null);
				System.out.println("interrupted(after consumer) ? " + isInterrupted());
			} catch (Exception e) {
				System.err.println("error occured: " + e.getMessage());
			}

			closeQuietly(consumer, session, connection);
		}

		private void waitForInterrupt() {
			try {
				TimeUnit.DAYS.sleep(Long.MAX_VALUE);
			} catch (InterruptedException e) {
				Thread.currentThread().interrupt();
			}
		}

		private void closeQuietly(Consumer consumer, Session session, Connection connection) {
			if (consumer != null) {
				try {
					consumer.close();
				} catch (AMQPException e) {
					System.err.println("error occured: " + e.getMessage());
				}
			}

			if (session != null) {
				session.close();
			}

			if (connection != null) {
				connection.close();
			}
		}
	}
}
```

**Comment by iitsoftware** [comment]
Thanks for posting this.

The AMQP 1.0 (and all of SwiftMQ actually, except if we use callbacks) almost uses this code to wait on results:

[https://github.com/iitsoftware/swiftmq-client/blob/develop/src/main/java/com/swiftmq/tools/concurrent/Semaphore.java](https://github.com/iitsoftware/swiftmq-client/blob/develop/src/main/java/com/swiftmq/tools/concurrent/Semaphore.java)

Basically a request is sent and served from some other thread and the above class is used to wait for the result to arrive. The Sempahore (actually a block) instance is passed to the other thread which releases the block and the initiating thread can continue.

This is a logic which was developed when the was no `Future` and other concurrency classes, btw.

The Semaphore is designed to be interruptible or not but the class that uses it decides. Almost non interruptible. At least I don't know a piece of code that handles interrupts. And I won't change that.

IMO, to base a logic on thread interrupts where you don't know what happens in libraries that holds the lock is at least non deterministic. I'd never do that.

**Comment by fross** [comment]
Quoting [Java Concurrency in Practice](https://www.amazon.com/Java-Concurrency-Practice-Brian-Goetz/dp/0321349601):

> A task should not assume anything about the interruption policy of its executing thread unless it is explicitly designed to run within a service that has a specific interruption policy. Whether a task interprets interruption as cancellation or takes some other action on interruption, **it should take care to preserve the executing thread's interruption status**. If it is not simply going to propagate InterruptedException  to its caller, it should restore the interruption status after catching InterruptedException: `Thread.currentThread().interrupt();`

I haven't look extensively at the code but preserving the Interrupt status should be doable where relevant. ie for [Semaphore.waitHere](https://github.com/iitsoftware/swiftmq-client/blob/develop/src/main/java/com/swiftmq/tools/concurrent/Semaphore.java): 
```
    public void waitHere() {
        lock.lock();
        try {
            while (!notified) {
                try {
                    if (interruptable)
                        waiter.await();
                    else
                        waiter.awaitUninterruptibly();
		} catch (InterruptedException e) {
			// restore interrupted status
			Thread.currentThread().interrupt();
                } catch (Exception ignored) {
                }
            }
        } finally {
            lock.unlock();
        }
    }
```

**Comment by fross** [comment]
Feel free to close the issue. It took me some time to figure out what was happening with the code I was running. I reviewed the logic to not rely on thread interrupt status. I still get intermittent deadlocks when closing consumers following a disconnection from the broker. I'll fill an issue if I find something. Have a nice day!

**Comment by iitsoftware** [comment]
I‘ve marked it as a bug (the other issue too). This project was closed source before so it might be there are more issues.

Feel free to contribute (use branch `develop`). Run the AMQP test suite thereafter. Thanks.
