### ISSUE TITLE
Consumer lock not released on receive if Link is closed

### ISSUE THREAD

**Issue by fross** [iitsoftware/swiftmq-client#31]
`cacheLock` doesn't seem to be released when invoking `receive` if Link is closed.

https://github.com/iitsoftware/swiftmq-client/blob/develop/src/main/java/com/swiftmq/amqp/v100/client/Consumer.java

```
private AMQPMessage receive(long timeout, MessageAvailabilityListener messageAvailabilityListener) {
	AMQPMessage msg = null;
	cacheLock.lock();
	if (closed)
		return null;
	try {
 		// ...
	} finally {
		cacheLock.unlock();
	}
	return msg;
}
```

**Comment by iitsoftware** [comment]
Moved all lock() ops into the try/finally and made all relevant booleans volatile.
