### ISSUE TITLE
AMQPUuid is broken

### ISSUE THREAD

**Issue by acogoluegnes** [iitsoftware/swiftmq-client#36]
The `AMQPUuid` class does not restore a passed-in UUID:

```java
UUID uuid = UUID.fromString("7d146cc0-7995-11ea-ab12-0800200c9a66");
AMQPUuid amqpUuid = new AMQPUuid(uuid);
System.out.println(uuid);
System.out.println(amqpUuid.getValue());
```

```
7d146cc0-7995-11ea-ab12-0800200c9a66
7d146cc0-ab12-0800-ab12-0800200c9a66
```

Unless I'm missing something, the 2 following pieces of code are wrong:

https://github.com/iitsoftware/swiftmq-client/blob/e5619a330ee082e646fd339a6a2eea7fbd1f5a4f/src/main/java/com/swiftmq/amqp/v100/types/AMQPUuid.java#L66-L70

https://github.com/iitsoftware/swiftmq-client/blob/e5619a330ee082e646fd339a6a2eea7fbd1f5a4f/src/main/java/com/swiftmq/amqp/v100/types/AMQPUuid.java#L77-L79

It should be 8 instead of 4.

I can submit a PR if my analysis is correct, but I cannot find how to run the test suite.

**Comment by iitsoftware** [comment]
Fixed and tested: https://github.com/iitsoftware/swiftmq-client/commit/60b9ddbad1c9e910d28aa90ecb642af2eb093028

Note: The fix is only available in branch `develop`.

Thanks for the report!

**Comment by acogoluegnes** [comment]
Thanks for the follow-up! Any ETA for 12.1.0?

**Comment by iitsoftware** [comment]
All issues for 12.1.0 concerning the SwiftMQ client are completed. So expect the release of the client very soon. SwiftMQ Router 12.1.0 may take a bit longer as we are waiting for a GraalVM fix.

**Comment by iitsoftware** [comment]
SwiftMQ Client 12.1.0 has been released right now. Takes a while until it shows up in Maven Central.

**Comment by acogoluegnes** [comment]
Got it, thanks for the follow-up!
