### ISSUE TITLE
AMQP 1.0 Client - Session not closed when end frame is received

### ISSUE THREAD

**Issue by ps-jho** [iitsoftware/swiftmq-client#44]
There seems to be an error in the AMQP 1.0 client where a `Session` and thereby also its `Link`s are not closed when an end frame is received from the remote server. Here are the AMQP frames for one `Session` where I experienced the problem:

```
amqp, SND[9] (size=42): [Begin nextOutgoingId=1, incomingWindow=100, outgoingWindow=100, handleMax=2147483647]
amqp, RCV[9] (size=28): [Begin remoteChannel=9, nextOutgoingId=1, incomingWindow=100, outgoingWindow=100, handleMax=7]
amqp, SND[9] (size=228): [Attach name=..., handle=0, role=TRUE, sndSettleMode=2, rcvSettleMode=0, source=[Source address=..., durable=0, expiryPolicy=link-detach, timeout=0, dynamic=FALSE], target=[Target address=..., durable=0, expiryPolicy=link-detach, timeout=0, dynamic=FALSE], incompleteUnsettled=FALSE]
amqp, SND[9] (size=51): [Flow nextIncomingId=1, incomingWindow=100, nextOutgoingId=1, outgoingWindow=100, handle=0, linkCredit=200, available=0, drain=FALSE, echo=FALSE]
amqp, RCV[9] (size=339): [Attach name=..., handle=0, role=FALSE, sndSettleMode=2, rcvSettleMode=0, source=[Source address=..., durable=0, expiryPolicy=link-detach, timeout=0, dynamic=FALSE], target=[Target address=..., durable=0, expiryPolicy=link-detach, timeout=0, dynamic=FALSE], incompleteUnsettled=FALSE, initialDeliveryCount=0, maxMessageSize=2147483647, properties=[...]]
amqp, RCV[9] (size=5427): [Transfer handle=0, deliveryId=0, deliveryTag=1E729994E1CB2A459F9B6869634E4F19, messageFormat=0, more=FALSE, resume=FALSE, aborted=FALSE, batchable=TRUE, body=[0, 0, 1E729994E1CB2A459F9B6869634E4F19, 0, NULL, FALSE, NULL, NULL, NULL, NULL, TRUE]] | payload size=5385
amqp, SND[9] (size=37): [Disposition role=TRUE, first=0, settled=FALSE, state=[Accepted ], batchable=TRUE]
amqp, RCV[9] (size=23): [Disposition role=FALSE, first=0, settled=TRUE, state=[Accepted ], batchable=FALSE]
amqp, RCV[9] (size=5428): [Transfer handle=0, deliveryId=1, deliveryTag=E8A0B142EB6E8F4CBB7D58291CA7BB4C, messageFormat=0, more=FALSE, resume=FALSE, aborted=FALSE, batchable=TRUE, body=[0, 1, E8A0B142EB6E8F4CBB7D58291CA7BB4C, 0, NULL, FALSE, NULL, NULL, NULL, NULL, TRUE]] | payload size=5385
amqp, SND[9] (size=41): [Disposition role=TRUE, first=1, settled=FALSE, state=[Accepted ], batchable=TRUE]
amqp, RCV[9] (size=24): [Disposition role=FALSE, first=1, settled=TRUE, state=[Accepted ], batchable=FALSE]
amqp, RCV[9] (size=15): [End ]
```

The problems is that after the end frame has been received `consumer.isClosed()` still returns `false`, so there's no way of knowing that it's been closed and that no further messages will be received.

I've looked a bit at the code of the AMQP client and found this method in `com.swiftmq.amqp.v100.client. ConnectionDispatcher` that I think handles the remote end frame:

```
public void visit(EndFrame frame) {
    if (pTracer.isEnabled()) pTracer.trace(toString(), ", visit=" + frame);
    if (frame.getError() == null)
        dispatchSession(frame.getChannel(), new POSessionFrameReceived(frame));
    else {
        Session session = myConnection.getSessionForRemoteChannel(frame.getChannel());
        if (session != null)
            session.remoteEnd(frame.getError());
    }
}
```

As you can see, `session.remoteEnd()` is only called if the end frame contains an error. Is this the expected behaviour? I would think `session.remoteEnd()` should be called regardless of whether the end frame contains an error or not.

**Comment by edgebroker** [comment]
It certainly has a reason why I dispatch the frame to the session if there is no error.  I have to check the AMQP 1.0 spec on this.

**Comment by edgebroker** [comment]
Checked. An `End` frame ends a session. However, it must be sent from both sides. Usually, the close of a session is initiated from the client side which leads to sending an `End` frame. The session is closed (with all resources) when the remote side sends an `End` frame, too. This remote `End` frame doesn't contain an error, so we use it as indicator that it is a reply to the client's `End` frame. 

`SessionDispatcher`:

```
    private void checkBothSidesEnd() {
        if (endPO != null && remoteEnd != null) {
            endPO.setSuccess(true);
            endPO.getSemaphore().notifySingleWaiter();
            endPO = null;
        }
    }

```
So this part is for the client initiated session end.

A remote session end usually contains an error so we call `session.remoteEnd` here, which initiates sending an `End` frame from the client.

**Comment by ps-jho** [comment]
@edgebroker Thanks for looking into it!

The problem is that in my case the client does receive an end frame with no error that is not a reply to an end frame sent by the client and as a result the `Session` instance on the client side remains open with me oblivious to the fact that it's really closed and that I won't receive any more messages. In addition, since I'm unaware that it has happened I can't try to recover by for instance creating a new `Session` and `Consumer`.

I'm no AMQP expert, but from a quick glance at the specification it seems like both sides can end a session and that there is no requirement for specifying an error. From section _2.5.2 Ending A Session_ of the [AMQP specification](https://docs.oasis-open.org/amqp/core/v1.0/amqp-core-complete-v1.0.pdf) (emphasis mine):

> Sessions are explicitly ended when **either endpoint** chooses to end the session. When a session is explicitly ended, an end frame is sent to announce the disassociation of the endpoint from its outgoing channel, and to carry error information **when relevant**.

So your assumption that a received end frame without an error is necessarily a reply to an end frame sent by the client does not seem to hold.

**Comment by edgebroker** [comment]
My comment wasn't meant that the current implementation is correct. ;-) 

I'll mark this issue as a bug. Thanks for reporting!

**Comment by iitsoftware** [comment]
Sorry, took a bit longer to dive into it as I was very busy.

I've committed a fix: https://github.com/iitsoftware/swiftmq-client/commit/6399540543eae27253c7cd29e81c04d1de372111

I have problems creating a test case for that. But you should have one. Can you test that? The commit is in branch `develop`.

Thanks.

**Comment by iitsoftware** [comment]
Nevermind. I was able to test it and works fine. A new release of the client will be available soon.
