### ISSUE TITLE
12.3.0 requires Java 11?

### ISSUE THREAD

**Issue by acogoluegnes** [iitsoftware/swiftmq-client#49]
I get `class file has wrong version 55.0, should be 52.0` when I try to compile a project with 12.3.0 on Java 8. It works on Java 11. It seems Java 11 is a requirement now, is that intended?

**Comment by iitsoftware** [comment]
You are quick. We are in the middle of release and did not update the docs yet. And yes, 12.3.0 requires Java 11+.

**Comment by acogoluegnes** [comment]
You are quick too  :)  I just happened to check the dependencies at that moment. OK, thanks for the heads-up.
